@php
  $dcComicsLinks => [
    [ "name" => "characters"],
    [ "name" => "comics"],
    [ "name" => "movies"],
    [ "name" => "tv"],
    [ "name" => "games"],
    [ "name" => "videos"],
    [ "name" => "news"],
  ],
  $shop => [
    [ "name" => "shop dc"],
    [ "name" => "shop dc collectibles"],
  ],
  $dc => [
    [ "name" => "terms of use"],
    [ "name" => "privacy policy (new)"],
    [ "name" => "ad choices"],
    [ "name" => "advertising"],
    [ "name" => "jobs"],
    [ "name" => "subscription"],
    [ "name" => "talent workshop"],
    [ "name" => "cpsc certificates"],
    [ "name" => "ratings"],
    [ "name" => "shop help"],
    [ "name" => "contact us"],
  ],
  $sites => [
    [ "name" => "dc"],
    [ "name" => "mad magazine"],
    [ "name" => "dc kids"],
    [ "name" => "dc universe"],
    [ "name" => "dc power visa"],
  ],
@endphp